# Generated by Django 5.0.4 on 2024-07-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('orangtua_wali', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('riwayat_pendidikan', models.TextField()),
                ('asal_sekolah', models.CharField(max_length=100)),
                ('tanggal_masuk', models.DateField()),
                ('asrama', models.CharField(choices=[('A', 'Asrama A'), ('B', 'Asrama B'), ('C', 'Asrama C')], max_length=1)),
                ('kamar', models.CharField(choices=[('A1', 'Kamar A1'), ('A2', 'Kamar A2'), ('A3', 'Kamar A3'), ('A4', 'Kamar A4'), ('A5', 'Kamar A5'), ('B1', 'Kamar B1'), ('B2', 'Kamar B2'), ('B3', 'Kamar B3'), ('B4', 'Kamar B4'), ('B5', 'Kamar B5'), ('C1', 'Kamar C1'), ('C2', 'Kamar C2'), ('C3', 'Kamar C3'), ('C4', 'Kamar C4'), ('C5', 'Kamar C5')], max_length=2)),
            ],
        ),
    ]
